version: "3.7"

services: 
  front:
    image: node:16
    container_name: front
    working_dir: /data/front
    restart: always
    build: ./front/
    volumes:
      - ./front/:/data/front/
      - /data/front/node_modules/
    ports:
      - "3000:3000"
  back:
    image: node:16
    container_name: back
    working_dir: /data/back
    restart: always
    build: ./back/
    volumes:
      - ./back/:/data/back/
      - /data/back/node_modules/
    ports:
      - "5000:5000"
