version: "3.7"

services: 
  front:
    image: node:16
    container_name: front
    working_dir: /data/front
    command: bash -c "yarn install && yarn dev"
    restart: always
    volumes:
      - ./front/:/data/front/
      - ./front/node_modules/:/data/front/node_modules/
      - ./front/.next/:/front/back/.next/
    ports:
      - "3000:3000"
  back:
    image: node:16
    container_name: back
    working_dir: /data/back
    command: bash -c "yarn install && yarn dev"
    restart: always
    volumes:
      - ./back/:/data/back/
      - ./back/node_modules/:/data/back/node_modules/
    ports:
      - "5000:5000"
  # blockchaindb:
  #   image: bigchaindb:2.2.2
  #   container_name: blockchaindb
  #   working_dir: /data/blockchaindb
  #   restart: always
  #   volumes:
  #     - ./blockchaindb/:/data/blockchaindb/
  #   ports:
  #     - "9984:9984"
